version: '3.4'

services:
  database:
    image: mariadb:10.3
    restart: always
    volumes:
      - ./.docker/mysql.cnf:/etc/mysql/conf.d/custom.cf:ro
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app

  app:
    build:
      context: .docker/
    depends_on:
      - database
    volumes:
      - ./:/var/www/html:rw,cached
      - ~/.composer:/var/www/html/.composer
      - sf-cache:/var/www/html/var/cache:rw
    networks:
      - app

  nginx:
    image: nginx:1.14-alpine
    links:
      - app:app
    volumes:
      - ./public:/var/www/html/public:ro
      - ./.docker/nginx.default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "88:80"
    depends_on:
      - database
    networks:
      - app

volumes:
  db-data: {}
  sf-cache: {}

networks:
  app:
    driver: 'bridge'